audio:
  auto_gain_control: false
  bit_depth: 16
  channels: 1
  chunk_size: 256
  echo_cancellation: false
  format: !!python/object/apply:src.coda.components.voice.models.AudioFormat
  - wav
  noise_reduction: false
  sample_rate: 16000
  silence_duration_ms: 1000
  vad_enabled: false
  vad_threshold: 0.5
conversation_mode: !!python/object/apply:src.coda.components.voice.models.ConversationMode
- turn_based
dynamic_allocation: false
enable_traditional_pipeline: false
external_llm:
  context_window: 8192
  fallback_enabled: false
  model: mock://llm
  parallel_processing: false
  provider: mock
  reasoning_mode: basic
  temperature: 0.7
  vram_allocation: 1GB
fallback_tts_model: xtts_v2
fallback_whisper_model: large-v3
memory_integration_enabled: false
mode: !!python/object/apply:src.coda.components.voice.models.VoiceProcessingMode
- moshi_only
moshi:
  device: cpu
  enable_streaming: false
  external_llm_enabled: false
  inner_monologue_enabled: true
  max_conversation_length: 300
  model_path: mock://moshi
  optimization: none
  target_latency_ms: 100
  vram_allocation: 1GB
personality_integration_enabled: false
reserved_system: 1GB
tools_integration_enabled: false
total_vram: 8GB
websocket_events_enabled: false
